apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: app-1
   #  these labels are deployment related labels
  labels:
    app: app2
    purpose: ingress 
spec:
  # modify replicas according to your case
  selector: 
    matchLabels:
      app: app2
      purpose: ingress
        # pod definition
  template: 
    metadata:
      labels:
        app: app2
        purpose: ingress
    spec:
      containers:
      - name: app2 
        image: joindevops/app2:1.0
---
apiVersion: v1 
kind: Service 
metadata:
  name: app2 
spec:
  selector:
    app: app2
    purpose: ingress
  ports:
  - protocol: TCP
    port: 80 #service-port
    targetPort: 80 #target-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        kubernetes.io/ingress.class: alb
        alb.ingress.kubernetes.io/target-type: ip
        alb.ingress.kubernetes.io/subnets: subnet-05e1c98ed0f5b109e,subnet-07f5bb81f661df61b,subnet-0a4e6232630820516
        alb.ingress.kubernetes.io/tags: Environment=dev,Team=dev  #tags
        # this annotation is useful to keep only ALB under srinath group.
        alb.ingress.kubernetes.io/group.name: Srinath
spec:
  ingressCLassName: alb
  rules:
  - host: "app2.srinath.online" #ALB rule
    http:
      paths:
      - pathType: Prefix
        path: "/bar"
        backend:
          service:
            name: app2 # ALB Target Group
            port:
              number: 80